kind: pipeline
type: docker
name: smart-contract-default

trigger:
  event:
    exclude:
      - promote

steps:
  - name: install deps
    image: node:18.12.1
    pull: always
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: check format
    image: node:18.12.1
    commands:
      - npm run check-format

  - name: compile smart contracts
    image: node:18.12.1
    commands:
      - npm run compile

  - name: test smart contracts
    image: node:18.12.1
    commands:
      - npm run test
---
# deploy smart contract in prod or dev
kind: pipeline
type: docker
name: deploy smart contract

trigger:
  event:
    - promote
  target:
    - smart-contract-dev
    - smart-contract-production
  branch:
    - develop
    - main

steps:
  - name: install deps
    image: node:18.12.1
    pull: always
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: check format
    image: node:18.12.1
    commands:
      - npm run check-format

  - name: compile smart contracts
    image: node:18.12.1
    commands:
      - npm run compile

  - name: test smart contracts
    image: node:18.12.1
    commands:
      - npm run test

  - name: smart-contract dev deployment
    image: node:18.12.1
    environment:
      WALLET_PRIVATE_KEY:
        from_secret: deployer-dev-privatekey
    commands:
      - npm run deploy
    when:
      target:
        - smart-contract-dev
      branch:
        - develop

  - name: smart-contract prod deployment
    image: node:18.12.1
    environment:
      WALLET_PRIVATE_KEY:
        from_secret: deployer-prod-privatekey
    commands:
      - npm run deploy
    when:
      target:
        - smart-contract-production
      branch:
        - main
---
# pipeline to add ressource to whitelist smart contract
kind: pipeline
type: docker
name: add-ressource-to-whitelist

trigger:
  event:
    - promote
  target:
    - add-ressource-to-whitelist-dev
    - add-ressource-to-whitelist-prod
  branch:
    - develop
    - main

steps:
  - name: install deps
    image: node:18.12.1
    pull: always
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: check format
    image: node:18.12.1
    commands:
      - npm run check-format

  - name: compile smart contracts
    image: node:18.12.1
    commands:
      - npm run compile

  - name: test smart contracts
    image: node:18.12.1
    commands:
      - npm run test

  - name: add ressource to whitelist
    image: node:18.12.1
    params:
      - CONTRACT_ADDRESS
      - ADDRESS_TO_ADD
    environment:
      WALLET_PRIVATE_KEY:
        from_secret: deployer-dev-privatekey
    commands:
      - npm run addRessourceToWhitelist
