name: Deploy contracts

on:
  workflow_dispatch: # Manual trigger
    inputs:
      network:
        description: 'Network'
        required: true
        type: choice
        options:
          - hardhat
          - bellecour
          - arbitrumSepolia
          - arbitrum
        default: 'hardhat'

jobs:

  # Build and test before deploying.
  build-and-test:
    uses: ./.github/workflows/main.yml

    deploy:
      needs: build-and-test
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.network == 'hardhat' }}
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to Hardhat
          run: npm run deploy -- --network hardhat

    
