name: Deploy contracts

on:
  workflow_dispatch: # Manual trigger
    inputs:
      network:
        description: 'Network'
        required: true
        type: choice
        options:
          - hardhat
          - bellecour
          - arbitrumSepolia
          - arbitrum
        default: 'hardhat'
      whitelist_owner:
        description: 'Whitelist contract owner address (optional - defaults to deployer)'
        required: false
        type: string

jobs:

  # Build and test before deploying.
  build-and-test:
    uses: ./.github/workflows/main.yml

  # Deploy and verify contract.
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      CI: true
    permissions:
      contents: write # Required to commit deployment files.
    environment: ${{ inputs.network }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci

      - name: Deploy contracts
        env:
          HARDHAT_IGNITION_CONFIRM_DEPLOYMENT: false
          PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          RPC_URL: ${{ secrets.RPC_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          WHITELIST_OWNER: ${{ inputs.whitelist_owner }}
        run: |
          if [ "${{ inputs.network }}" != "hardhat" ]; then
            npm run deploy -- --network ${{ inputs.network }} --verify
          else
            npm run deploy -- --network ${{ inputs.network }}
          fi

      - name: Save deployment artifacts
        if: inputs.network != 'hardhat'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: save deployment artifacts for ${{ inputs.network }} (${{ github.run_id }})'
          file_pattern: 'config/config.json broadcast/'
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'GitHub Actions Bot <github-actions[bot]@users.noreply.github.com>'
